from __future__ import annotations

import functools
from enum import Enum
from pathlib import Path

from pydantic import BaseModel, Field
from pydantic_settings import BaseSettings, SettingsConfigDict


class Provider(str, Enum):
    """Supported LLM backend providers."""

    ANTHROPIC = "anthropic"
    OPENAI = "openai"
    OLLAMA = "ollama"


class TaskModel(BaseModel):
    """A single unit of work generated by the planner."""

    id: str
    description: str
    files: list[str] = Field(default_factory=list)
    dependencies: list[str] = Field(default_factory=list)
    status: str = "pending"
    result: str | None = None


class Plan(BaseModel):
    """A plan composed of ordered tasks plus the reasoning that produced it."""

    tasks: list[TaskModel]
    rationale: str


class TestResult(BaseModel):
    """Outcome of running the test suite and/or semantic test verdict."""

    passed: bool
    summary: str
    failures: list[str] = Field(default_factory=list)


class Settings(BaseSettings):
    """Runtime configuration loaded from environment variables and a .env file.

    Environment variables use the ``FURROW_`` prefix (e.g. ``FURROW_PROVIDER``).
    """

    model_config = SettingsConfigDict(env_prefix="FURROW_", env_file=".env")

    provider: Provider = Field(
        default=Provider.ANTHROPIC,
        description="LLM provider used for planning, working and testing.",
    )
    model: str = Field(
        default="claude-sonnet-4-20250514",
        description="Default model used when no role-specific model is configured.",
    )
    planner_model: str = Field(
        default="claude-3-5-haiku-20241022",
        description="Model used by the planner agent.",
    )
    worker_model: str = Field(
        default="claude-3-5-sonnet-20241022",
        description="Model used by the worker agent.",
    )
    tester_model: str = Field(
        default="claude-3-5-sonnet-20241022",
        description="Model used by the tester agent for the semantic pass/fail verdict.",
    )
    anthropic_api_key: str | None = Field(
        default=None,
        description="API key for the Anthropic provider.",
    )
    openai_api_key: str | None = Field(
        default=None,
        description="API key for the OpenAI provider.",
    )
    ollama_base_url: str = Field(
        default="http://localhost:11434",
        description="Base URL of the local Ollama server.",
    )
    max_parallel_tasks: int = Field(
        default=5,
        description="Maximum number of tasks executed concurrently within a single cycle.",
    )
    max_cycles: int = Field(
        default=10,
        description="Maximum planner/worker cycles allowed before stopping. "
        "Defaults to 10 to prevent runaway loops; set to 0 for unlimited.",
    )
    workspace: Path = Field(
        default_factory=Path.cwd,
        description="Root directory the agent operates within.",
    )
    log_level: str = Field(
        default="INFO",
        description="Python logging level for furrow.",
    )


@functools.lru_cache(maxsize=1)
def get_settings() -> Settings:
    """Build and cache the :class:`Settings` instance lazily.

    Constructing settings at import time can surface partially-configured
    environments early; deferring construction avoids this while still caching
    the result so repeated access is cheap.
    """
    return Settings()


# Backwards-compatible alias.
settings = get_settings()
