from __future__ import annotations

import json
import os
import re
from pathlib import Path

from furrow.agents.prompts import WORKER_PROMPT
from furrow.config import TaskModel
from furrow.llm import LLMClient


class WorkerAgent:
    def __init__(self, task: TaskModel, client: LLMClient | None = None) -> None:
        self.task = task
        self.client = client or LLMClient()
        self.workspace = Path(self.client.settings.workspace)

    async def run(self) -> str:
        prompt = f"{WORKER_PROMPT}\n\nTask: {self.task.description}\nFiles to touch: {', '.join(self.task.files) if self.task.files else 'any'}\n"
        response = await self.client.complete(prompt, model=self.client.settings.worker_model)
        await self._apply_changes(response)
        return response

    async def _apply_changes(self, response: str) -> None:
        # Try to extract file blocks from the response and write them to disk
        pattern = re.compile(r"```(?:[a-zA-Z]*\n)?(.*?)```", re.DOTALL)
        matches = list(pattern.finditer(response))

        for match in matches:
            block = match.group(1).strip()
            if "\n" not in block and len(block) < 100:
                continue
            # Heuristic: first line is a filename comment or path
            first_line = block.split("\n")[0].strip()
            candidate_path = None
            if first_line.startswith("# ") or first_line.startswith("// "):
                candidate_path = first_line.lstrip("# ").lstrip("// ").strip()
            elif "/" in first_line or "\\" in first_line:
                candidate_path = first_line

            if candidate_path:
                file_path = self.workspace / candidate_path
                content = "\n".join(block.split("\n")[1:]).strip()
                if content:
                    await self.client.write_file(file_path, content)
                    continue

        # If no structured blocks found, try to write files explicitly mentioned in the task
        if self.task.files and not matches:
            for filename in self.task.files:
                file_path = self.workspace / filename
                file_path.parent.mkdir(parents=True, exist_ok=True)
                # Only create empty placeholder files if they don't exist
                if not file_path.exists():
                    await self.client.write_file(file_path, f"# Auto-generated by Furrow\n# Task: {self.task.id}\n")
